version: "3"
services:
  installer:
    build: docker/installer
    depends_on:
      - php_fpm
    volumes:
      - .:/var/app
  nginx:
    build: docker/nginx
    depends_on:
      - php_fpm
      - php_fpm_debug
    volumes:
      - .:/var/app:delegated
    ports:
      - "80:80"
    #  - "8000:8000"
      - "8001:8001"
  php_fpm:
    build: docker/php_fpm
    image: phpdoctool_php_fpm
    volumes:
      - .:/var/app:delegated
  php_fpm_debug:
    build: docker/php_fpm_debug
    depends_on:
      - php_fpm
    volumes:
      - .:/var/app:delegated
  redis:
    image: redis:4.0.6
    ports:
      - "6379:6379"
    volumes:
      - .:/var/www
    command: ["redis-server", "/var/www/docker/redis/config/redis.conf"]

