version: "3"
services:
  installer:
    build: docker/installer
    volumes:
      - .:/var/app
  nginx:
    build: docker/nginx
    depends_on:
      - php_fpm
      - php_fpm_debug
    volumes:
      - .:/var/app
    ports:
      - "80:80"
      - "8000:8000"
      - "8001:8001"
  php_fpm:
    build: docker/php_fpm
    image: phpdoctool_php_fpm
    volumes:
      - .:/var/app
  php_fpm_debug:
    build: docker/php_fpm_debug
    depends_on:
      - php_fpm
    volumes:
      - .:/var/app
